apiVersion: v1
kind: ReplicationController
metadata:
  name: spring-controller
spec:
  replicas: 1
  selector:
    app: springboot
  template:
    metadata:
      name: springboot
      labels:
        app: springboot
    spec:
      containers:
        - name: springboot
          image: ghousebablu/spring-boot-mongo
          ports:
            - containerPort: 8080
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  name: springboot
spec:
  type: NodePort
  selector:
    app: springboot
  ports:
  - port: 8080
    targetPort: 8080
---
# Mongo host path rc
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-controller
spec:
  replicas: 1
  selector:
    app: mongo
  template:
    metadata:
      name: mongo
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
              hostPort: 27017
          volumeMounts:
          - name: mongo-persistent-storage
            mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        hostPath:
         path: /tmp/dbbackup
---
# Mongo Node Port RC
apiVersion: v1
kind: Service
metadata:
  name: mongosvc
spec:
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017
